name: 블로그 포스팅 README에 추가
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
       logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
       tags:
          description: 'Test scenario tags'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: '6'
          feed_list: 'https://evan-moon.github.io/feed.xml'
          template: '<sup>[$title]($url)</sup>$newline'
